site_name: "Joker Blog"
site_url:  "http://blog.jokerhub.cn"
site_description: "This is my personal blog"
site_author: "wangzhizhou"

repo_url: "https://github.com/wangzhizhou/JokerBlog"
repo_name: "JokerBlog"

google_analytics: ["UA-36723568-3", "mkdocs.org"]
copyright: "Created by Wang Zhizhou"

theme: 
  name: 'material'
  palette:
    primary: 'Green'
    accent: 'Orange'
  font: 
    text: 'Roboto Slab'
    code: 'Ubuntu Mono'
  language: 'zh'
  direction: 'ltr'
  favicon: 'img/favicon.ico'
  feature:
    tabs: true


markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - 'javascripts/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - 'stylesheets/extra.css'

extra:
  disqus: 'jokerhub-blog'
  social:
    - type: 'github'
      link: 'https://github.com/wangzhizhou'
    - type: 'twitter'
      link: 'https://twitter.com/w_z_z_1991'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/wangzhizhou'

nav:
    - 主页:
        - 简介: 'index.md'
        - 博客创建过程: 'How I create this blog.md'
    - 工作:
        - 校招求职: 'job/My Plan for finding Job.md'
        - 社招面试: "iOS/review.md"
        - 面试准备资料: "iOS/job-plan.md"
        - 离职: 'job/dimission.md'
    - 生活:
        - 支付宝集福: 'life/alipay-scan-fu-icon.md'
        - 北京租房: 'life/Renting in Beijing.md'
        - 古北水镇游玩: 'life/Gu Bei Shui Zhen.md'
        - 乌镇游玩: 'life/WuZhen.md'
    - Geek:
        - WireGuard: 'geek/wireguard.md'
        - Git核心技能: 'geek/Git.md'
        - Ubuntu安装NS2网络模拟器: 'geek/Network Simulator 2 Installation Guide for Ubuntu.md'
        - 30分钟掌握STL: 'geek/Learn STL In 30 Minutes.md'
        - U盘安装Ubuntu: 'geek/Installation of Ubuntu 16.04 On UDisk.md'
        - 搭建Git服务: 'geek/Configure Git Server With Ubuntn and Apache 2.md'
        - OpenCV给视频添加水印: 'geek/User OpenCV to add watermark on a video.md'
        - OpenCV+FFmpeg给视频添加水印: 'geek/Add Watermark on Video with OpenCV and FFmpeg.md'
        - DLNA开发: 'geek/Develop DLNA Using Platinum Library.md'
        - Nmap基础: 'geek/Nmap Basics.md'
        - GDB使用: 'geek/Use GDB.md'
        - Kotlin学习: 'geek/kotlin.md'
        - jupyterhub工具使用: 'geek/jupyterhub.md'
        - bluegogo破解: 'geek/bluegogo-crack.md'
        - FFmpeg:
            - FFmpeg教程: 'geek/FFmpeg and SDL tutorial 1.md'
            - Mac上编译FFmpeg: 'geek/FFmpeg compiled on MacOS.md'
            - FFmpeg示例代码学习: 'geek/FFmpeg version 3.1.4 example code.md'
            - FFmpeg转码学习: 'geek/Fmpeg 2.8.6 example code - transcoding.md'
            - 使用FFmpeg将MP4转成GIF图片: 'geek/Convert MP4 to GIF With FFmpeg.md'
        - Jenkins:
            - 导览: jenkins/guide/index.md
            - 第一个管道: jenkins/guide/first-pipeline.md
            - 多步管道: jenkins/guide/multiple-steps-pipeline.md
            - 定义执行环境: jenkins/guide/define-execution-environments.md
            - 使用环境变量: jenkins/guide/using-environment-variables.md
            - 记录测试结果: jenkins/guide/recording-test-results-and-artifacts.md
            - 清理和通知: jenkins/guide/cleaning-up-and-notification.md
            - 布署: jenkins/guide/deployment.md
        - ReactiveX:
            - 介绍: reactiveX/introduction.md
            - 可观察的: reactiveX/Observable.md
            - 运算符: reactiveX/Operators.md
            - 单事件可观察对象: reactiveX/Single.md
            - 主题: reactiveX/Subject.md
            - 调度器: reactiveX/Scheduler.md
        - Docker:
            - 简介: docker/start-learn.md
            - 定位: docker/Orientation.md
            - 容器: docker/Container.md
            - 服务: docker/Service.md
            - 机群: docker/Swarm.md
            - 栈: docker/Stack.md
            - 部署应用: docker/Deploy.md
        - Nginx:
            - 新手教程: nginx/beginner-guide.md
            - 主要用途: nginx/application.md
        - iOS:
            - 工作流: "iOS/workflow.md"
            - 持续集成: "iOS/XCode 9 CI.md"
            - Swift4: "iOS/swift4-notes.md"
            - Swift5: "iOS/swift5-notes.md"
            - Swift在客户端和服务端的使用: 'geek/swift on client and server.md'
            - 服务端Swift:
                - 第四章Swfit包管理器: "iOS/swift-on-server/[4]Swift-Package-Manager.md"
                - 第五章使用Kitura写ToDoList: "iOS/swift-on-server/[5]Writng-ToDoList-With-Kitura.md"
            - OC相关: "iOS/objc.md"
            - 逆向工程: "iOS/reverse.md"
            - 应用优化: "iOS/optimization.md"
            - 优化应用启动时长: 'geek/Optimizing App Startup Time.md'
            - 十大排序算法: "iOS/sort.md"
            - OC运行时编译: "iOS/runtime.md"
            - 线程编码指南: "iOS/TPG.md"
            - 并发编码指南: "iOS/CPG.md"
            - 设计模式: "iOS/design-pattern.md"
            - 测试驱动开发: "iOS/TDD.md"
            - AirDrop社交: "iOS/airdrop.md"
        - 乐理基础: 
            - 乐音:
                - "music/theory/tones/Pitches and Clefs.md"
            - 节拍:
                - "music/theory/rhythms/Note Values and Basic Notation.md"
            - 曲调:
                - "music/theory/tunes/Melodies.md"
            - 伴奏:
                - "music/theory/accompanying/Transcribing What You Hear.md"
            - 修饰:
                - "music/theory/embellishing/Harmony and Counterpoint.md"
            - 编曲:
                - "music/theory/arranging/composing and arranging for voices and instruments.md"
            - 附录:
                - "music/theory/appendixes/A.md"
    - 关于我: 
        - 理财: 'me/My Financial Planning.md'
        - 人在北京: 'me/Life in Beijing.md'
        - 硬件: 'me/my hardware.md'
        - 早起记录: 'me/Personal Pre-Work Record.md'
        